baseURL = '/'
languageCode = 'en-us'
title = 'theref.eth'
theme = 'archie'
relativeURLs = true
canonifyURLs = false

[params]
  # most themes use params for social links; adjust keys to your theme
  github = "theref"
  farcaster = "theref.eth"